# Generated by Django 2.2.1 on 2019-05-27 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=30)),
                ('slug', models.CharField(max_length=40)),
                ('image', models.FileField(blank=True, upload_to='')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=3000)),
            ],
        ),
    ]
